start
goslammu/yp_go_devops pull request #1
Opened 2022-11-13 13:49 UTC by goslammu

2022-11-14 16:09 UTC, bambruysk requested changes
А почему предыдущей работы нет в этом репо?

2022-11-16 10:14 UTC, goslammu commented on cmd/staticlint/exitcheck.go
> +				return true
Исправлено.

2022-11-16 10:14 UTC, goslammu commented on cmd/staticlint/exitcheck.go
> +	for _, file := range pass.Files {
Исправлено.

2022-11-16 11:58 UTC, goslammu commented on internal/pkg/agent/send.go
> +	log.Println("SEND METRIC: ", res.Status, res.Request.URL)
Исправлено.

2022-11-16 12:13 UTC, goslammu commented on internal/pkg/agent/send.go
> +	if er := res.Body.Close(); er != nil {
Исправлено.

2022-11-16 12:35 UTC, goslammu commented on internal/pkg/agent/send.go
> +	if er := res.Body.Close(); er != nil {
Исправлено.

2022-11-16 12:35 UTC, goslammu commented on internal/pkg/agent/storage.go
> +		if er := allMetrics[i].UpdateHash(agn.config.HashKey); er != nil {
Исправлено.

2022-11-16 12:59 UTC, goslammu commented on internal/pkg/compresser/compresser.go
> +			log.Println(err.Error())
Исправлено.

2022-11-16 13:00 UTC, goslammu commented on internal/pkg/agent/storage.go
> +			return 0, errors.New("cannot get <" + name + ">: core number error")
Исправлено.

2022-11-16 13:17 UTC, goslammu commented on internal/pkg/agent/send.go
> +	return client, nil
Исправлено.

2022-11-16 13:27 UTC, goslammu commented on internal/pkg/agent/storage.go
> +func (agn *agent) getCustomMetricValue(name string) (float64, error) {
Исправлено.

2022-11-16 13:33 UTC, goslammu commented on internal/pkg/pgxstorage/pgxstorage.go
> +		if !success {
Исправлено.

2022-11-16 14:44 UTC, goslammu commented on internal/pkg/server/server.go
> +				for {
Исправлено.

2022-11-16 14:44 UTC, goslammu commented on internal/pkg/server/server.go
> +	} else if srv.config.FileDestination != "" {
Исправлено.

2022-11-16 15:09 UTC, goslammu commented on internal/pkg/pgxstorage/pgxstorage_test.go
> +			if tt.Name != "empty id" && tt.Name != "nil input" {
Исправлено.

2022-11-16 16:28 UTC, goslammu commented on internal/pkg/pgxstorage/pgxstorage.go
> +	CREATE TABLE IF NOT EXISTS ` + tabname + ` ` + schema
Исправлено.

2022-11-19 08:36 UTC, bambruysk approved these changes
Аппрув, потом что замечания в основном относятся к предыдущим инкрементам. Но код явно стоит порефачить. И в части архитекутуры тоже

2022-11-19 08:36 UTC, bambruysk commented on cmd/server/migrations/metrics
> +	(
Здесь должен быть прям SQL. Чтобы можно было выполнить и проверить что все работает.  То есть добавить сюда. CREATE TABLE IF NOT EXISTS metrics

2022-11-19 08:36 UTC, bambruysk commented on internal/pkg/agent/report.go
> +		} else {
Обрати внимание - если случайно дропнуть фигурную скобку перед else то код скомпилируется но работать будет неправильно. Лучше после вложенного if использовать conitnue  и не использовать else

2022-11-19 08:36 UTC, bambruysk commented on internal/pkg/agent/storage.go
> +func getCustomMetricValue(name string) (float64, error) {
Функции нужно делать как можно короче - на примере этой можно показать как разбить ее на насколько.

```
// Collects custom metric by it's name. Implements individual algorithms for custom metrics.
func getCustomMetricValue(name string) (float64, error) {
	switch {
	case name == RandomValue:
		return getRandomValue()
	case name == TotalMemory:
		return getTotalMemory()
	case name == FreeMemory:
		return getFreeMemory()
	case strings.Contains(name, CPUutilization):
		return getCPUutilization(name)
	default:
		return 0, fmt.Errorf("cannot get: unsupported metric <%v>", name)
	}
}

func getCPUutilization(name string) (float64, error) {
	procUsage, err := cpu.Percent(0, true)
	if err != nil {
		return 0, err
	}
	num, err := strconv.ParseInt(strings.TrimPrefix(name, CPUutilization), 10, 64)
	if err != nil {
		return 0, err
	}
	if int(num) > len(procUsage) {
		return 0, fmt.Errorf("cannot get <%v>: core number error", name)
	}
	return procUsage[num-1], nil
}

func getFreeMemory() (float64, error) {
	vm, err := mem.VirtualMemory()
	if err != nil {
		return 0, err
	}
	return float64(vm.Free), nil
}

func getTotalMemory() (float64, error) {
	vm, err := mem.VirtualMemory()
	if err != nil {
		return 0, err
	}
	return float64(vm.Total), nil
}

func getRandomValue() (float64, error) {
	return 100 * rand.Float64(), nil
}
```
В  другиз местах стоит обращать внимание на размер методов и функций и даже стоит настроить линтер на это (размер не только в строках но и сложность

2022-11-19 08:36 UTC, bambruysk commented on internal/pkg/server/server.go
> +func (srv *server) initStorage() error {
тоже стоит разбить на несколько

2022-11-19 08:36 UTC, bambruysk commented on internal/pkg/server/handlers.go
> +		http.Error(w, err.Error(), http.StatusNotFound)
А если сторадж вернет ошибку соединения с БД или валидации входного запроса все равно будет 400?

2022-11-21 20:18 UTC, merged